# Generated by Django 2.1.1 on 2018-09-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TimeReport',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay_date', models.DateTimeField()),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='report.Employee')),
                ('job_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='report.JobGroup')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='report.TimeReport')),
            ],
        ),
    ]
