# Generated by Django 2.1.1 on 2018-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_payrollfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollfile',
            name='title',
        ),
        migrations.AlterField(
            model_name='payrollfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
