# Generated by Django 2.1.1 on 2018-09-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20180928_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgroup',
            name='compensation',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
