version: '3'

services:
  db:
    image: postgres

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend/dockerfile
    volumes:
      - ./backend:/app
    tty: true
    stdin_open: true
    env_file: ./dockerfiles/backend/env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend/dockerfile
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    command: npm run dev
