version: '3'

services:
  db:
    image: postgres

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend/dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python --version

  frontend:
    build:
      context: .
      dockerfile: ./dockerfiles/frontend/dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run dev
