services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend/Dockerfile
    volumes:
      - ./backend:/backend
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver

  web:
    build:
      context: .
      dockerfile: dockerfiles/web/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DEPLOY='development'
    command: npm run dev
