 FROM python:3.6
 RUN apt-get update && apt-get install -y \
	postgresql \
	postgresql-contrib \
	postgresql-client

 RUN mkdir /app
 WORKDIR /app
 ADD ./backend/requirements.txt /app/requirements.txt
 RUN pip install -r requirements.txt
 EXPOSE 8000
 ADD ./backend /app
#  RUN chmod +x /app/wait-for-postgres.sh TODO: prevents possible race condition on boot
